"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.27.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

# Standard library imports
import os
from pathlib import Path

# Third-party imports
from dotenv import load_dotenv
from datetime import timedelta

# Load environment variables
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DEBUG", "False").lower() == "true"


# HMAC
HMAC_SHARED_SECRET = os.getenv("HMAC_SHARED_SECRET", "supersecretkey")
HMAC_ALLOWED_DRIFT_SECONDS = int(os.getenv("HMAC_ALLOWED_DRIFT_SECONDS", "300"))
HMAC_NONCE_TTL_SECONDS = int(os.getenv("HMAC_NONCE_TTL_SECONDS", "600"))


# JWT
JWT_SECRET = os.getenv("JWT_SECRET", "supersecretjwtsecret")
JWT_ALGORITHM = os.getenv("JWT_ALGORITHM", "HS256")
JWT_ACCESS_TTL = timedelta(minutes=int(os.getenv("JWT_ACCESS_TTL", "60")))
JWT_REFRESH_TTL = timedelta(days=int(os.getenv("JWT_REFRESH_TTL", "7")))


# AWS S3 Configuration
AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID")
AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY")
AWS_STORAGE_BUCKET_NAME = os.getenv("AWS_STORAGE_BUCKET_NAME")
AWS_S3_REGION_NAME = os.getenv("AWS_S3_REGION_NAME", "us-east-1")
AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com"
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = "public-read"
AWS_S3_OBJECT_PARAMETERS = {
    "CacheControl": "max-age=86400",
}

# Allowed hosts and CSRF trusted origins
# TODO: Add your production domain here (e.g., "yourdomain.com")
ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
]

# TODO: Add your production domain here (e.g., "https://yourdomain.com")
CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1:8000",
]


# Application definition
INSTALLED_APPS = [
    # Django built-in apps
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    # Third-party apps
    "django_cron",
    "drf_spectacular",
    "widget_tweaks",
    
    # Local apps
    "api",
]

# Cache Configuration using Redis
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0"),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

# Django Cron Configuration
# TODO: Register your cron job classes here, e.g.:
# CRON_CLASSES = [
#     "api.cron.example_cron.ExampleCronJob",
# ]

# REST Framework Configuration
REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Throttling Configuration
    'DEFAULT_THROTTLE_CLASSES': [
        'api.throttling.BurstRateThrottle',
        'api.throttling.SustainedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'burst': '60/min',                 # Burst limit: 60 requests per minute
        'sustained': '1000/hour',          # Sustained limit: 1000 requests per hour
        'auth_token': '5/min',             # Auth endpoints: 5 per minute (strict security)
        'data_modification': '30/min',     # Data modification: 30 per minute
        'content_listing': '30/min',       # Content listing/discovery: 30 per minute
        'search': '20/min',                # Search queries: 20 per minute (stricter)
        'admin': '100/hour',               # Admin operations: 100 per hour
    },
    
    # Custom Exception Handler
    'EXCEPTION_HANDLER': 'api.exceptions.custom_exception_handler',
}

# API Documentation Settings
SPECTACULAR_SETTINGS = {
    # Basic API info
    # TODO: Update the title and description for your project
    'TITLE': 'Django Backend API',
    'DESCRIPTION': '''Welcome to the Django Backend API documentation.

## Getting Started
1. **Get your token**: Use the `/api/v1/auth/get-token/` endpoint (POST) to obtain a JWT token
2. **Authorize**: Click the "Authorize" button at the top right
3. **Enter token**: Paste your JWT token and click "Authorize"
4. **Test endpoints**: All protected endpoints will now work with your token

## Rate Limiting
All endpoints are protected by IP-based rate limiting:
- **Authentication**: 5 requests/min (strict security)
- **Search Queries**: 20 requests/min (expensive operations)
- **Content Listing**: 30 requests/min (feeds, playlists, etc.)
- **Data Modification**: 30 requests/min (POST/PUT/PATCH operations)
- **Global Default**: 60 requests/min burst + 1000 requests/hour sustained

If you exceed rate limits, you will receive a `429 Too Many Requests` response with retry time.

## Response Format
All responses follow a consistent format with `success`, `message`, and `data` fields.''',
    'VERSION': '1.0.0',
    'CONTACT': {
        'name': 'API Support',
    },

    # Disable automatic /api/schema/
    'SERVE_INCLUDE_SCHEMA': False,

    # Security schemes - this makes the Authorize button appear
    'APPEND_COMPONENTS': {
        'securitySchemes': {
            'bearerAuth': {
                'type': 'http',
                'scheme': 'bearer',
                'bearerFormat': 'JWT',
                'description': 'Enter your JWT token obtained from the /auth/token endpoint'
            }
        }
    },
    'SECURITY': [{'bearerAuth': []}],

    'AUTHENTICATION_WHITELIST': [],

    # Swagger UI tweaks
    'SWAGGER_UI_SETTINGS': {
        'persistAuthorization': True,
        'displayRequestDuration': True,
        'filter': True,
        'tryItOutEnabled': True,
        'defaultModelsExpandDepth': 2,
        'defaultModelExpandDepth': 2,
    },
    
    # Sort endpoints by method
    'SORT_OPERATIONS': False,
    
    # TODO: Update tags to match your project's API groups
    'TAGS': [
        {'name': 'Authentication', 'description': 'Get and verify JWT tokens'},
        {'name': 'Device Registration', 'description': 'Device registration and management'},
        # Add your project-specific tags here, e.g.:
        # {'name': 'Items', 'description': 'Item management'},
        # {'name': 'Categories', 'description': 'Category management'},
    ],
    
    # Enable preprocessing to find Django View classes
    'PREPROCESSING_HOOKS': [
        'drf_spectacular.hooks.preprocess_exclude_path_format',
    ],
    
    # Generate schema for all views including Django View
    'COMPONENT_SPLIT_REQUEST': True,
}



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.getenv("MYSQL_DB_NAME"),
        "USER": os.getenv("MYSQL_DB_USER"),
        "PASSWORD": os.getenv("MYSQL_DB_PASSWORD"),
        "HOST": os.getenv("MYSQL_DB_HOST"),
        "PORT": os.getenv("MYSQL_DB_PORT"),
        "OPTIONS": {
            "charset": "utf8mb4",
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise Configuration - Serves static files in production
# For Django 4.2+, use STORAGES instead of STATICFILES_STORAGE
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
AUTH_USER_MODEL = "api.User"

